/**
 * Free Trial Configuration
 * Based on Implementasi_Free_Trial_BerkahKarya.docx
 */

export const FREE_TRIAL_CONFIG = {
  welcomeBonus: {
    enabled: true,
    type: 'image_generation',
    count: 1,
    provider: 'google_gemini', // FREE provider
  },
  dailyFree: {
    enabled: true,
    type: 'image_generation',
    count: 1,
    resetTime: '00:00', // WIB
    provider: 'google_gemini',
  },
  restrictions: {
    promptSource: 'library_only', // Must choose from niche library
    customPrompt: false, // Must pay for custom
    watermark: true, // "Generated by BerkahKarya"
    queuePriority: 'lowest', // Subscribers prioritized
    videoGeneration: false, // Only image is free
  },
};

export interface UserFreeTrial {
  welcomeBonusUsed: boolean;
  dailyFreeUsed: boolean;
  dailyFreeResetAt: Date | null;
  selectedNiche: string | null;
}

export function canUseWelcomeBonus(user: any): boolean {
  return !user.welcomeBonusUsed;
}

export function canUseDailyFree(user: any): boolean {
  if (!user.dailyFreeResetAt) return true;
  
  const now = new Date();
  const resetAt = new Date(user.dailyFreeResetAt);
  
  // Check if reset time has passed (00:00 WIB = UTC+7)
  return now >= resetAt;
}

export function getNextDailyFreeReset(): Date {
  const now = new Date();
  const tomorrow = new Date(now);
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(0, 0, 0, 0); // 00:00 WIB
  return tomorrow;
}
