/**
 * Free Trial Configuration
 * Based on Implementasi_Free_Trial_BerkahKarya.docx
 */

export const FREE_TRIAL_CONFIG = {
  welcomeBonus: {
    enabled: true,
    type: 'image_generation',
    count: 1, // 1 free image only, on first use
    provider: 'google_gemini',
  },
  dailyFree: {
    enabled: true, // Daily mystery prompt showcase (no free generation, just prompt discovery)
    type: 'prompt_showcase',
    count: 1,
    resetTime: '00:00', // WIB
    provider: 'google_gemini',
  },
  restrictions: {
    promptSource: 'library_only', // Must choose from niche library
    customPrompt: false, // Must pay for custom
    watermark: true, // "Generated by BerkahKarya"
    queuePriority: 'lowest', // Subscribers prioritized
    videoGeneration: false, // Only image is free
  },
};

export interface UserFreeTrial {
  welcomeBonusUsed: boolean;
  dailyFreeUsed: boolean;
  dailyFreeResetAt: Date | null;
  selectedNiche: string | null;
}

export function canUseWelcomeBonus(user: any): boolean {
  return !user.welcomeBonusUsed;
}

export function canUseDailyFree(user: any): boolean {
  if (!FREE_TRIAL_CONFIG.dailyFree.enabled) return false;
  // If no reset time is set but daily free was already used, deny access
  if (!user.dailyFreeResetAt) return !user.dailyFreeUsed;

  const now = new Date();
  const resetAt = new Date(user.dailyFreeResetAt);
  return now >= resetAt;
}

export function getNextDailyFreeReset(): Date {
  // Calculate "tomorrow midnight" in WIB (UTC+7), then convert back to UTC
  const WIB_OFFSET_MS = 7 * 60 * 60 * 1000;
  const nowWib = new Date(Date.now() + WIB_OFFSET_MS);
  const tomorrowWib = new Date(nowWib);
  tomorrowWib.setUTCDate(tomorrowWib.getUTCDate() + 1);
  tomorrowWib.setUTCHours(0, 0, 0, 0);
  return new Date(tomorrowWib.getTime() - WIB_OFFSET_MS);
}
